# Generated by Django 5.0.6 on 2024-06-24 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('date', models.DateField()),
                ('date2', models.DateField()),
                ('problem', models.TextField()),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hospitalapp.doctorinformation')),
            ],
        ),
    ]
