# Generated by Django 5.0.6 on 2024-06-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_appointmentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcaresolutions',
            name='icon',
            field=models.CharField(default='asgkl;;', max_length=50),
        ),
    ]
