# Generated by Django 5.0.6 on 2024-06-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_alter_appointmentform_date2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentForm',
            new_name='AppointmentFormModel',
        ),
    ]
