# Generated by Django 5.0.6 on 2024-06-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_rename_appointmentform_appointmentformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcaresolutions',
            name='seconds',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
